### ISSUE TITLE
是个报错（恼

### ISSUE THREAD

**Issue by XiaoTong6666** [MrXiaoM/mirai-console-dev-qrlogin#1]
Login failed: net.mamoe.mirai.internal.network.auth.ProducerFailureException
2023-03-27 05:35:09 E/console: net.mamoe.mirai.internal.network.auth.ProducerFai
lureException
net.mamoe.mirai.internal.network.auth.ProducerFailureException
        at net.mamoe.mirai.internal.network.auth.CoroutineOnDemandValueScope.rec
eiveOrNull(CoroutineOnDemandValueScope.kt:152)
        at net.mamoe.mirai.internal.network.auth.AuthControl.acquireAuth(AuthCon
trol.kt:98)
        at net.mamoe.mirai.internal.network.components.SsoProcessorImpl.login(Ss
oProcessor.kt:219)
        at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$StateCo
nnecting$startState$2.invokeSuspend(CommonNetworkHandler.kt:247)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Contin
uationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineS
cheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(C
oroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(Cor
outineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(Coroutine
Scheduler.kt:664)
        Suppressed: net.mamoe.mirai.network.UnsupportedQRCodeCaptchaException: T
his login session requires QRCode login, but current LoginSolver(com.kasukusakur
a.mlss.resolver.SakuraLoginSolver@b9f501e) does not support it. Please override
`LoginSolver.createQRCodeLoginListener`.
                at net.mamoe.mirai.utils.LoginSolver.createQRCodeLoginListener(L
oginSolver.kt:66)
                at net.mamoe.mirai.internal.network.components.QRCodeLoginProces
sorPreLoaded.prepareProcess(QRCodeLoginProcessor.kt:60)
                at net.mamoe.mirai.internal.network.components.SsoProcessorImpl.
login(SsoProcessor.kt:235)
                at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$
login$1.invokeSuspend(SsoProcessor.kt)
                at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWit
h(ContinuationImpl.kt:33)
                at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes
.kt:33)
                at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCorou
tine.kt:102)
                at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWit
h(ContinuationImpl.kt:46)
                at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFu
nctionGun.resumeRootWith(SuspendFunctionGun.kt:138)
                at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFu
nctionGun.loop(SuspendFunctionGun.kt:112)
                at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFu
nctionGun.access$loop(SuspendFunctionGun.kt:14)
                at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFu
nctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:62)
                at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWit
h(ContinuationImpl.kt:46)
                at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFu
nctionGun.resumeRootWith(SuspendFunctionGun.kt:138)
                at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFu
nctionGun.loop(SuspendFunctionGun.kt:112)
                at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFu
nctionGun.access$loop(SuspendFunctionGun.kt:14)
                at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFu
nctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:62)
                at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWit
h(ContinuationImpl.kt:46)
                at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFu
nctionGun.resumeRootWith(SuspendFunctionGun.kt:138)
                at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFu
nctionGun.loop(SuspendFunctionGun.kt:112)
                at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFu
nctionGun.access$loop(SuspendFunctionGun.kt:14)
                at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFu
nctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:62)
                at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWit
h(ContinuationImpl.kt:46)
                at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFu
nctionGun.resumeRootWith(SuspendFunctionGun.kt:138)
                at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFu
nctionGun.loop(SuspendFunctionGun.kt:112)
                at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFu
nctionGun.access$loop(SuspendFunctionGun.kt:14)
                at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFu
nctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:62)
                at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWit
h(ContinuationImpl.kt:46)
                at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFu
nctionGun.resumeRootWith(SuspendFunctionGun.kt:138)
                at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFu
nctionGun.loop(SuspendFunctionGun.kt:112)
                at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFu
nctionGun.access$loop(SuspendFunctionGun.kt:14)
                at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFu
nctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:62)
                at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWit
h(ContinuationImpl.kt:46)
                ... 5 more
        Suppressed: net.mamoe.mirai.internal.network.handler.selector.SelectorRe
quireReconnectException
Caused by: [CIRCULAR REFERENCE: net.mamoe.mirai.network.UnsupportedQRCodeCaptcha
Exception: This login session requires QRCode login, but current LoginSolver(com
.kasukusakura.mlss.resolver.SakuraLoginSolver@b9f501e) does not support it. Plea
se override `LoginSolver.createQRCodeLoginListener`.]

2023-03-27 05:35:09 I/Bot.36********6: Bot cancelled: Bot closed

**Comment by XiaoTong6666** [comment]
最主要是本小白看不懂呐，用的win8.1，jdk版本是17（没啥限制吧

**Comment by xiaotong6666** [comment]
问了下chatgpt，它是这么回答我的：
似乎是由于ProducerFailureException导致登录失败。堆栈跟踪表明身份验证过程可能存在问题。错误消息还指示登录会话需要Qrcode登录，但当前LoginSolver不支持它。你可能需要重写“Logunver”。创建Qrcode登录侦听器的方法以支持Qrcode登录。或者，您可以尝试使用当前LoginSolver支持的其他登录方法。也有可能身份验证服务器或网络连接有问题，因此您可能也要检查这些问题。

**Comment by XiaoTong6666** [comment]
嗯，我把报错发给了chatgpt，它是这么说的：
“
这段错误信息是来自一个名为"Mamoe Mirai"的聊天机器人框架。它在进行身份验证时遇到了一个名为"ProducerFailureException"的错误。具体错误信息如下：

登录失败：net.mamoe.mirai.internal.network.auth.ProducerFailureException
在"CoroutineOnDemandValueScope.kt"文件的第152行，CoroutineOnDemandValueScope类的receiveOrNull()方法抛出了这个异常。
在"AuthControl.kt"文件的第98行，AuthControl类的acquireAuth()方法被调用，但在执行过程中产生了异常。
在"SsoProcessor.kt"文件的第219行，SsoProcessorImpl类的login()方法被调用，但在执行过程中产生了异常。
在"CommonNetworkHandler.kt"文件的第247行，CommonNetworkHandler类的StateConnecting$startState$2方法被调用，但在执行过程中产生了异常。
其他的代码都是异常处理和调度相关的。

这段错误信息还提到了一个名为"UnsupportedQRCodeCaptchaException"的错误，并指出需要使用"QRCode"进行登录。但当前的登录程序不支持QRCode登录，需要在代码中进行相应的修改来支持QRCode登录。
*
使用的是2.15.0-M1，难道说这版本不能用嘛qwq

**Comment by MrXiaoM** [comment]
login solver sakura 覆盖了登录解决器，但 sakura 还没有实现二维码登录的解决器。这是 sakura 的问题

**Comment by XiaoTong6666** [comment]
ok，解决了
