### ISSUE TITLE
在本地登录后把bots文件夹丢服务器上后仍然要求扫码登录

### ISSUE THREAD

**Issue by Apricityx** [MrXiaoM/mirai-console-dev-qrlogin#2]
如题，gocqhttp扫码后把session.token丢服务器上就能正常登录，mirai是否有类似的解决办法
已使用/qrAutoLogin add <account>指定自动登录的账号
使用协议：ANDROID_WATCH
MACOS首次登录没问题，第二次登录就报code45

**Comment by MrXiaoM** [comment]
有没有一种可能是你切换ip太频繁了它才要求你重新扫码

**Comment by Apricityx** [comment]
是这样的，但我看gocqhttp没有要求重新扫码，是实现方式不同吗



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年4月15日(周六) 凌晨1:22
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [MrXiaoM/mirai-console-dev-qrlogin] 在本地登录后把bots文件夹丢服务器上后仍然要求扫码登录 (Issue #2)




 
有没有一种可能是你切换ip太频繁了它才要求你重新扫码

**Comment by MrXiaoM** [comment]
我不研究协议，我不知道

**Comment by Apricityx** [comment]
那就是说没有除搭代理之外的解决方法了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年4月15日(周六) 凌晨1:30
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [MrXiaoM/mirai-console-dev-qrlogin] 在本地登录后把bots文件夹丢服务器上后仍然要求扫码登录 (Issue #2)




 
我不研究协议，我不知道

**Comment by Apricityx** [comment]
已解决，解决方法是用服务器搭socks代理，用手机连接后ip就一致了，再扫码即可
