### ISSUE TITLE
二维码在shell输出

### ISSUE THREAD

**Issue by XiaoTong6666** [MrXiaoM/mirai-console-dev-qrlogin#3]
您好大佬，又是我，我又来提issues了（小声）
是这样的，之前用这个qrlogin都是在有桌面环境的操作系统上使用的，但是刚刚在ubuntu server系统上没有桌面环境下跑
![Screenshot_2023-04-30-01-38-31-690_com sonelli juicessh](https://user-images.githubusercontent.com/110387028/235321737-9705a981-958d-42e0-886d-7430d01bc6d1.jpg)
就是它甚至不保存个图片到本地（控制台没说报错二维码）
如果它报错了我还可以新建立一个ssh用TerminalImageViewer来输出下（但是......）
所以我就想问下大佬，可以在没有桌面环境的情况下报错个图片嘛（有可能我是例外？）青取于蓝的gocq都有直接输出了
![Screenshot_2023-04-30-03-40-02-526_bin mt plus](https://user-images.githubusercontent.com/110387028/235321956-bd0fba0a-0bf3-4c2e-a4c4-04a0d306a0d7.jpg)
（比如这个
所以望佬答！！
₍˄·͈༝·͈˄*₎◞ ̑̑

**Comment by MrXiaoM** [comment]
日志不全

**Comment by MrXiaoM** [comment]
消极提供信息，你的 issue 将以无效状态关闭，并禁止你的访问。
